name: Prod - Website CI/CD
on:
  push:
    branches:
    - main

jobs:
  prod_deploy:
    name: 'Prod Website Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{ github.repository }}

      - name: Echo directory
        run: ls -lha ${{ github.repository }}

      - name: Log event name
        run: echo "This is the ${{ github.event_name }} event for branch ${{ github.ref }} in repository ${{ github.repository }}."

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with: 
          aws-region: ${{ vars.AWS_PROD_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
      - name: Deploy to S3
        run: aws s3 sync ./${{ github.repository }} s3://${{ vars.AWS_PROD_BUCKET_NAME }} --delete --exclude ".git/*" --exclude ".github/*"

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.AWS_PROD_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"